import React from "react";

const TermsAndConditions = () => {
  const containerStyle = {
    marginTop: "80px",
    padding: "20px",
    maxWidth: "800px",
    margin: "0 auto",
    fontFamily: "Arial, sans-serif",
    color: "#333",
    lineHeight: "1.6",
    textAlign: "justify",
  };

  const headingStyle = {
    fontSize: "24px",
    fontWeight: "bold",
    marginBottom: "20px",
    textAlign: "center",
  };

  return (
    <div style={containerStyle}>
      <h1 style={headingStyle}>Terms &amp; Conditions</h1>
      <p>
        This document is an electronic record in terms of Information Technology
        Act, 2000 and rules there under as applicable and the amended provisions
        pertaining to electronic records in various statutes as amended by the
        Information Technology Act, 2000. This electronic record is generated by
        a computer system and does not require any physical or digital
        signatures.
      </p>

      <p>
        This document is published in accordance with the provisions of Rule 3
        (1) of the Information Technology (Intermediaries guidelines) Rules,
        2011 that require publishing the rules and regulations, privacy policy
        and Terms of Use for access or usage of domain name{" "}
        <a href="https://www.lewkout.com">https://www.lewkout.com</a>{" "}
        ("Website"), including the related mobile site and mobile application
        (hereinafter referred to as "Platform").
      </p>

      <p>
        The Platform is owned by Lewkout, a company incorporated under the
        Companies Act, 1956 with its registered office at 117, Salasar Enclave,
        Nandkishorepura, Manyawas, Jaipur (hereinafter referred to as “Platform
        Owner”, "we", "us", "our").
      </p>

      <p>
        Your use of the Platform and services and tools are governed by the
        following terms and conditions ("Terms of Use") as applicable to the
        Platform including the applicable policies which are incorporated herein
        by way of reference. If You transact on the Platform, You shall be
        subject to the policies that are applicable to the Platform for such
        transaction. By mere use of the Platform, You shall be contracting with
        the Platform Owner and these terms and conditions including the policies
        constitute Your binding obligations, with Platform Owner.
      </p>

      <p>
        These Terms of Use relate to your use of our website, goods (as
        applicable) or services (as applicable) (collectively, "Services"). Any
        terms and conditions proposed by You which are in addition to or which
        conflict with these Terms of Use are expressly rejected by the Platform
        Owner and shall be of no force or effect. These Terms of Use can be
        modified at any time without assigning any reason. It is your
        responsibility to periodically review these Terms of Use to stay
        informed of updates.
      </p>

      <p>
        For the purpose of these Terms of Use, wherever the context so requires
        "you", "your" or "user" shall mean any natural or legal person who has
        agreed to become a user/buyer on the Platform.
      </p>

      <p>
        ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR
        AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO
        PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
      </p>

      <h3>Key Terms</h3>
      <ul>
        <li>
          You agree to provide true, accurate and complete information during
          and after registration.
        </li>
        <li>
          Neither we nor third parties provide any warranty or guarantee as to
          the accuracy, timeliness, performance, completeness or suitability of
          the information and materials offered on this website.
        </li>
        <li>
          Your use of the Services and the Platform is solely at your own risk.
        </li>
        <li>
          The contents of the Platform and the Services are proprietary to us.
        </li>
        <li>
          Unauthorized use may lead to action against you as per applicable
          laws.
        </li>
        <li>
          You agree not to use the Platform/Services for unlawful purposes.
        </li>
        <li>
          Third-party links are governed by their own terms and privacy policy.
        </li>
        <li>
          You shall indemnify and hold harmless Platform Owner and its
          affiliates against claims arising from your breach of Terms, policies,
          or violation of laws/rights.
        </li>
        <li>
          Parties shall not be liable for any failure to perform obligations if
          prevented or delayed by a force majeure event.
        </li>
      </ul>

      <p>
        These Terms and any dispute or claim relating to it, or its
        enforceability, shall be governed by and construed in accordance with
        the laws of India. All disputes shall be subject to the exclusive
        jurisdiction of the courts in Jaipur, Rajasthan.
      </p>

      <p>
        All concerns or communications relating to these Terms must be
        communicated to us using the contact information provided on this
        website.
      </p>
    </div>
  );
};

export default TermsAndConditions;
